# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Atualizações para pacotes NuGet (C#)
  - package-ecosystem: "nuget"
    directory: "/" # ou o caminho onde está o seu arquivo .csproj ou .sln
    schedule:
      interval: "daily"

  # Atualizações para npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Atualizações para Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
